version: '3.4'

services:
  ApiServer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:9095
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  WebApp:
    # environment:
    #    NODE_ENV: development
    ports:
      - 4200:4200
    # - 9229:9229
    # command: ["node", "--inspect=0.0.0.0:9229", "index.js"]