version: '3.4'

services:
  ApiServer:
    image: api-server:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  WebApp:
    image: web-app:dev
    # environment:
    #    NODE_ENV: development
    ports:
      - 4200:4200
    # - 9229:9229
    # command: ["node", "--inspect=0.0.0.0:9229", "index.js"]


