version: '3.4'
volumes:
  productdata:

services:
  ApiServer:
    image: api-server:latest
    build:
      context: .
      dockerfile: BackupDB.API/Dockerfile
    ports:
     - 9095:9095
    volumes:
      - productdata:/app
    #network_mode: host
    environment:
        - ASPNETCORE_URLS=http://localhost:9095

  WebApp:
    image: web-app:latest
    build:
      context: BackupDB-SPA
      dockerfile: ./Dockerfile
    # environment:
    #   NODE_ENV: production
    ports:
      - 4200:4200


